name: Build and deploy Node.js app to Azure Web App - QuoteItDiscordBot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: '20.x' # More stable than 22.x

      - name: Install dependencies
        run: npm ci
        env:
          CI: true

      - name: Run build (if available)
        run: npm run build --if-present

      - name: Run tests (if available)
        run: npm test --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip . -x '*.git*' 'node_modules/*'

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'QuoteItDiscordBot'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_09BE437CFCE14418B7BCDDD54805FE1A }}
