# .github/workflows/main_quoteitbot.yml (or your bot's workflow filename)

name: Build and Deploy Discord Bot to Azure App Service

on:
  push:
    branches:
      - main
    paths: # Adjust if your bot code isn't at the root or if you have other projects
      - '**'
      - '!.github/workflows/**' # Don't trigger on changes to other workflows
      - '.github/workflows/main_quoteitbot.yml' # Trigger on changes to this workflow itself
      - '!README.md'
  workflow_dispatch:

jobs:
  build_and_package_bot:
    name: Build and Package Discord Bot
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Debug - Show current directory (Repo Root) and list files
        working-directory: ${{ github.workspace }} # Explicitly run at repo root
        run: |
          echo "--- Current directory (should be Repo Root): $(pwd) ---"
          echo "--- Listing files in Repo Root: ---"
          ls -la
          echo "--- Contents of package.json: ---"
          cat package.json || echo "package.json not found in $(pwd)"

      - name: Install Bot Dependencies
        working-directory: ${{ github.workspace }} # Assumes package.json is at repo root
        run: npm ci

      # - name: Build Bot Application (if applicable)
      #   working-directory: ${{ github.workspace }}
      #   run: npm run build --if-present

      - name: Prepare Bot Deployment Package
        working-directory: ${{ github.workspace }} # Operations from repo root
        run: |
          echo "--- Preparing deployment package from $(pwd) ---"
          # Create staging dir also in the workspace root
          mkdir -p ${{ github.workspace }}/deployment_package_bot_staging
          
          echo "--- Copying application files to staging directory... ---"
          cp package.json ${{ github.workspace }}/deployment_package_bot_staging/
          cp package-lock.json ${{ github.workspace }}/deployment_package_bot_staging/
          cp index.js ${{ github.workspace }}/deployment_package_bot_staging/
          
          if [ -d "utils" ]; then cp -r utils ${{ github.workspace }}/deployment_package_bot_staging/; fi
          if [ -d "commands" ]; then cp -r commands ${{ github.workspace }}/deployment_package_bot_staging/; fi
          # Add other necessary files/folders from the repository root

          echo "--- Contents of staging directory (deployment_package_bot_staging): ---"
          ls -la ${{ github.workspace }}/deployment_package_bot_staging

      - name: Zip Bot Deployment Package
        working-directory: ${{ github.workspace }} # Run zip command from repository root
        run: |
          echo "--- Zipping contents of deployment_package_bot_staging from $(pwd) ---"
          cd deployment_package_bot_staging
          zip -r ../discord-bot-release.zip ./*
          cd ..
          echo "--- Created discord-bot-release.zip in repository root ---"

      - name: Upload Bot Artifact
        uses: actions/upload-artifact@v4
        with:
          name: discord-bot-app-artifact
          path: discord-bot-release.zip

  deploy_bot_to_azure:
    name: Deploy Discord Bot to Azure App Service
    runs-on: ubuntu-latest
    needs: build_and_package_bot
    environment:
      name: 'Production_Bot' # Or your Azure environment name
      url: ${{ steps.deploy-to-bot-app-service.outputs.webapp-url }}
    permissions:
      id-token: write # Required for OIDC Azure login

    steps:
      - name: Download Bot Artifact
        uses: actions/download-artifact@v4
        with:
          name: discord-bot-app-artifact

      - name: Unzip Bot Artifact
        run: |
          unzip discord-bot-release.zip -d ./deploy_bot_content_final
          echo "--- Contents of deploy_bot_content_final after unzip: ---"
          ls -la ./deploy_bot_content_final

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BOT }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BOT }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BOT }}
          # Removed: auth-type: "oidc" 

      - name: Deploy to Azure App Service for Bot
        id: deploy-to-bot-app-service
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'QuoteIt' # !!! REPLACE WITH YOUR BOT'S ACTUAL APP SERVICE NAME !!!
          slot-name: 'Production' # Or your deployment slot
          package: ./deploy_bot_content_final # Directory containing unzipped package
